version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - env/local.env
    depends_on:
      - postgres
      - mongo

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: posgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: partdb
  #   ports:
  #     - "5432:5432"

  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
